### ISSUE TITLE
Add create wormsim flow to wormsim frontend

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#25]
**Tasks**:

- [x] Put together WormSim creation flow "tutorial" based on and mockups below (see comment from @tarelli). This entails reworking the wormsim frontend to create the flow in the mockups. The user will see this flow only the first time they login.
- [x] Make sure text on each step/screen is easily configurable
- [x] Open pull request to merge into development branch

Notes: would be good to modularize as much as possible but no need for each of the steps in the flow to be components, as this will be only used in the context of the wormsim frontend.

**Comment by tarelli** [comment]
Mockups for this, note, the background is a 3D canvas, the spotlight is an actual THREE spotlight, between the first and the second mockup the camera smoothly transitions to a close up of the worm. The font is Helvetica Neue ultralight. The color of the custom writings (blue in the mockups) will depend on what colour the user will pick. Use colour pick functionality on the mockups to get the exact RGB of the colours.
![mockupstart](https://cloud.githubusercontent.com/assets/81127/7202159/fa272aba-e50f-11e4-9fe8-9e58a41929f0.png)
![mockupcolour](https://cloud.githubusercontent.com/assets/81127/7202160/fd7c7530-e50f-11e4-92c0-779b93a3e241.png)
![mockupname](https://cloud.githubusercontent.com/assets/81127/7202164/fffa2730-e50f-11e4-9aed-d46a403cdd57.png)
![mockupdone](https://cloud.githubusercontent.com/assets/81127/7202165/02a7d162-e510-11e4-95b7-8fb1f598eb7e.png)

**Comment by mihairaulea** [comment]
alice in wornderland font for the last page

**Comment by mihairaulea** [comment]
http://seeklogo.com/alice-in-wonderland-font-1335.html
http://www.fontsquirrel.com/tools/webfont-generator
